[package]
name = "rust-os"
version = "0.1.0"
authors = ["mp3 <im.in.a.coma.xxx@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
