[package]
name = "rust-os"
version = "0.1.0"
authors = ["mp3 <im.in.a.coma.xxx@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.9.8"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
